import 'package:flutter/material.dart';

class CategoryIconRegistry {
  CategoryIconRegistry._();

  static final Map<String, IconData> icons = {
    'restaurant': Icons.restaurant,
    'restaurant_menu': Icons.restaurant_menu,
    'food_bank': Icons.food_bank,
    'local_dining': Icons.local_dining,
    'coffee': Icons.coffee,
    'local_cafe': Icons.local_cafe,
    'liquor': Icons.liquor,
    'shopping_cart': Icons.shopping_cart,
    'shopping_bag': Icons.shopping_bag,
    'local_grocery_store': Icons.local_grocery_store,
    'checkroom': Icons.checkroom,
    'directions_car': Icons.directions_car,
    'local_taxi': Icons.local_taxi,
    'commute': Icons.commute,
    'local_gas_station': Icons.local_gas_station,
    'flight': Icons.flight,
    'train': Icons.train,
    'directions_bus': Icons.directions_bus,
    'two_wheeler': Icons.two_wheeler,
    'home': Icons.home,
    'house': Icons.house,
    'electrical_services': Icons.electrical_services,
    'water_drop': Icons.water_drop,
    'receipt': Icons.receipt,
    'receipt_long': Icons.receipt_long,
    'description': Icons.description,
    'health_and_safety': Icons.health_and_safety,
    'local_hospital': Icons.local_hospital,
    'medical_services': Icons.medical_services,
    'school': Icons.school,
    'book': Icons.book,
    'menu_book': Icons.menu_book,
    'work': Icons.work,
    'business_center': Icons.business_center,
    'laptop': Icons.laptop,
    'computer': Icons.computer,
    'store': Icons.store,
    'storefront': Icons.storefront,
    'savings': Icons.savings,
    'account_balance': Icons.account_balance,
    'payments': Icons.payments,
    'wallet': Icons.wallet,
    'card_giftcard': Icons.card_giftcard,
    'celebration': Icons.celebration,
    'movie': Icons.movie,
    'sports_esports': Icons.sports_esports,
    'theater_comedy': Icons.theater_comedy,
    'fitness_center': Icons.fitness_center,
    'self_improvement': Icons.self_improvement,
    'pets': Icons.pets,
    'child_care': Icons.child_care,
    'phone_android': Icons.phone_android,
    'sim_card': Icons.sim_card,
    'wifi': Icons.wifi,
    'category': Icons.category,
    'more_horiz': Icons.more_horiz,
    'star': Icons.star,
    'favorite': Icons.favorite,
    'trending_up': Icons.trending_up,
    'trending_down': Icons.trending_down,
    'attach_money': Icons.attach_money,
    'money': Icons.money,
    'paid': Icons.paid,
    'construction': Icons.construction,
    'handyman': Icons.handyman,
    'clean_hands': Icons.clean_hands,
    'grass': Icons.grass,
    'spa': Icons.spa,
    'content_cut': Icons.content_cut,
    'calendar_month': Icons.calendar_month,
    'event': Icons.event,
    'music_note': Icons.music_note,
    'headphones': Icons.headphones,
    'umbrella': Icons.umbrella,
    'beach_access': Icons.beach_access,
    'terrain': Icons.terrain,
  };

  static IconData get(String key) => icons[key] ?? Icons.category;

  static List<MapEntry<String, IconData>> get all => icons.entries.toList();
}
